---
title: "Your Document Title"
author: "Author Name"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output: 
  pdf_document:
    includes:
      in_header: header.tex
geometry: "margin=0.87in" # 2.5 cm approx 0.984 inches, use 0.87in for closer approximation
fontsize: 12pt
mainfont: Times New Roman
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \rhead{Group Member Names}
  - \cfoot{\thepage}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(conflicted)
library(ggplot2)
library(GGally)
library(ggpubr)
library(tidyverse)
library(corrplot)
require(gridExtra)
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
```


```{r}
data <- read.csv('./data/beerhall.csv')
colnames(data)<- c("county", "region_name", "region_code", "criminals_100k", "ale_100k","school_attend_10k", "church_attend_2k")

writeLines("\nFirst few data elements:\n")
str(data)
writeLines("\n")
head(data)
writeLines("\n")

```
```{r}
# returns minimum, maximum, 1st quartile, median, mean and 3rd
#quartile of every variable
writeLines("Data summary:\n")
summary(data)
writeLines("\n")

```
```{r}
# plot variable-wise histograms
numeric_data <- data[, sapply(data, is.numeric)]
data %>% pivot_longer(cols = c(criminals_100k, ale_100k,school_attend_10k, church_attend_2k)) %>%
  ggplot(aes(value)) + facet_wrap(~ name, scales = "free") + geom_histogram()

```

```{r}
# analyse correlation between variables
par(mfrow = c(1, 1))
M <- cor(numeric_data)
corrplot(cor(numeric_data), method = "number")
```



```{r}
# regression plots
fig1 <- ggplot(data, aes(ale_100k, criminals_100k)) + geom_point() +
  stat_smooth(method = "lm")
fig2 <- ggplot(data, aes(school_attend_10k, criminals_100k)) + geom_point() +
  stat_smooth(method = "lm")
fig3 <- ggplot(data, aes(region_code, criminals_100k)) + geom_point() +
  stat_smooth(method = "lm")
fig4 <- ggplot(data, aes(church_attend_2k, criminals_100k)) + geom_point() +
  stat_smooth(method = "lm")

ggarrange(fig1, fig2, fig3, fig4)
```


