---
title: "Model Fitting"
output:
  html_document:
    df_print: paged
date: "2024-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Model Fitting

The model is fitted using polynomial regression. In order to predict Criminals per 100k population, we use a polynomial regression model which uses Ale/Beer Houses per 100k, Attendants @ school per 10k, and Attendants @ public worship per 2000 as the features.

Mathematically, the model can be represented as:

A polynomial regression model of degree n with three features (x1, x2, x3) can be represented as follows:

$y = \beta_0 + \beta_{11}x_1 + \beta_{12}x_1^2 + ... + \beta_{1n}x_1^n + \beta_{21}x_2 + \beta_{22}x_2^2 + ... + \beta_{2n}x_2^n + \beta_{31}x_3 + \beta_{32}x_3^2 + ... + \beta_{3n}x_3^n + \epsilon$

Where:

y is Criminals per 100k population
x1, x2, x3 are the independent variables [Ale/Beer Houses per 100k, Attendants @ school per 10k, and Attendants @ public worship per 2000]
β0, βij are the coefficients of the model where i is the feature index and j is the degree of the polynomial
ε is the error term

The model was chosen based on the Exploratory data analysis and the correlation between the features and the target variable. On top of the linear relation, we also add polynomial terms to capture the non-linear relation between the features and the target variable. The degree of the polynomial was chosen based on the cross-validation results, highlighted in the next section.
